### ISSUE TITLE
Update cohort on login not working in 4.0.1

### ISSUE THREAD

**Issue by chrispratt-tonyyeb** [moodle-an-hochschulen/moodle-local_profilecohort#40] opened 2022-05-20 20:56 UTC
Logging in with a new user does not update their cohort. Editing and saving their profile does, however.

**Comment by abias** [comment] 2022-08-05 18:42
Hi @tonyyeb ,

I am currently preparing the 4.0 release of this plugin and, against this background, tried to reproduce your finding here.
However, I was not able to reproduce it with Moodle 4.0.2.

Can you please try to reproduce it on the latest Moodle 4.0 release and, if you are still able to reproduce it, provide detailed steps to reproduce?

**Comment by abias** [comment] 2023-04-30 08:43
As there hasn't been any feedback on this issue anymore, I will close it now.

**Closed by abias** 2023-04-30 08:43 UTC
