### ISSUE TITLE
Delete rule not and move to position not working

### ISSUE THREAD

**Issue by intuitable** [moodle-an-hochschulen/moodle-local_profilecohort#49] opened 2022-10-17 13:18 UTC
We're having a problem trying to delete rules and move their position.

When we select a rule to be deleted, it does get highlighted and crossed out but when we hit save the rule it still shown.

When we try to move a rule, changing the value in the dropdown successfully moves the rule to the new position but when we hit save it returns to its previous position.

Are we doing something wrong?

Aside from that, this is a fantastic plugin that we could not live without!

Moodle version: 3.9.17
Plugin version: v4.0-r1 (2022071200)

**Comment by abias** [comment] 2023-04-30 15:59
Hi @intuitable ,

I am struggling to understand how you managed to install the v4.0-r1 version in a Moodle 3.9 as each of our releases for a new Moodle major release comes with raising the requirements of the Moodle major release. If you look at https://github.com/moodle-an-hochschulen/moodle-local_profilecohort/blob/0143ff80aff7ccf28f1198d04ace3400502de80d/version.php#L30, you will see that this plugin can't be installed on Moodle releases older than 4.0.

Against this background, I will close this issue for now as "can't reproduce". Please test again with a plugin version which matches the Moodle version you are running.

Cheers,
Alex

**Closed by abias** 2023-04-30 15:59 UTC
